---
title: "test"
author: "Priyam Patel"
date: "4/1/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(shiny)
library(plotly)
library(reshape)
library(forcats)
```

## R Markdown

```{r data, echo = FALSE}
pre = readRDS("D:/Priyam/Desktop/INFO550_Final/code/pre_seasons.rds")
reg = readRDS("D:/Priyam/Desktop/INFO550_Final/code/reg_seasons.rds")
post = readRDS("D:/Priyam/Desktop/INFO550_Final/code/post_seasons.rds")
```

```{r plot, echo = FALSE}
# https://rmarkdown.rstudio.com/lesson-14.html
selectInput("type", "Choose a game type",
            choices = c("Preseason", "Regular Season", "Postseason"))

selectInput("year", "Choose a season",
            choices = c("2009-2010" = 2009,
                        "2010-2011" = 2010,
                        "2011-2012" = 2011,
                        "2012-2013" = 2012,
                        "2013-2014" = 2013,
                        "2014-2015" = 2014,
                        "2015-2016" = 2015,
                        "2016-2017" = 2016,
                        "2017-2018" = 2017,
                        "2018-2019" = 2018,
                        "2019-2020" = 2019
                        ))

selectInput("dwn", "Choose a down",
            choices = c("1st Down" = 1,
                        "2nd Down" = 2,
                        "3rd Down" = 3,
                        "4th Down" = 4))


# Change this time remaining in quarter, add quarter selection box
sliderInput("time", "Maximum time remaining in game:",
                  min = 0, max = 60,
                  value = 1, step = 5,
                  animate =
                    animationOptions(interval = 300, loop = TRUE))


playData = reactive({
  req(input$dwn)
  req(input$year)
  req(input$time)
  switch(input$type,
         "Preseason" = pre %>%
           filter(Season == input$year, down == input$dwn, game_seconds_remaining <= input$time*60, !is.na(play_type)) %>%
           select(Season, game_seconds_remaining, down, yardline_100, play_type, epa),
         "Regular Season" = reg %>%
           filter(Season == input$year, down == input$dwn, game_seconds_remaining <= input$time*60, !is.na(play_type)) %>%
           select(Season, game_seconds_remaining, down, yardline_100, play_type, epa),
         "Postseason" = post %>%
           filter(Season == input$year, down == input$dwn, game_seconds_remaining <= input$time*60, !is.na(play_type)) %>%
           select(Season, game_seconds_remaining, down, yardline_100, play_type, epa))
})

# https://plotly.com/r/filled-area-plots
# For example, being on your own 20 yard line means you are 80 yards from their end zone, but being on their 20 yard line means you are 20 yards from their end zone.

# 
# renderTable(playData()%>%
#     group_by(yardline_100, play_type) %>%
#     summarize(plays = n()) %>%
#     ungroup() %>%
#     complete(play_type, nesting(yardline_100), fill = list(plays = 0)) %>%
#     arrange(yardline_100) %>%
#     group_by(yardline_100) %>%
#     mutate(play_pct = (plays/sum(plays))*100) %>%
#     cast(yardline_100~play_type))

renderPlotly(
  # playData() %>%
  #   group_by(yardline_100, play_type) %>%
  #   summarize(plays = n()) %>%
  #   ungroup() %>%
  #   complete(play_type, nesting(yardline_100), fill = list(plays = 0)) %>%
  #   arrange(yardline_100) %>%
  #   group_by(yardline_100) %>%
  #   mutate(play_pct = (plays/sum(plays))*100) %>%
  #   cast(yardline_100~play_type, value = 'plays') %>%
  #   plot_ly(
  #     x=~yardline_100, 
  #     y=~field_goal,
  #     name = "Field Goal",
  #     type = 'scatter', 
  #     mode = 'lines', 
  #     fill = 'tozeroy'
  #   ) %>% 
  #   add_trace(x = ~yardline_100, y = ~no_play, name = 'No Play', fill = 'tozeroy') %>%
  #   add_trace(x = ~yardline_100, y = ~pass, name = 'Pass', fill = 'tozeroy') %>%
  #   add_trace(x = ~yardline_100, y = ~qb_kneel, name = 'QB Kneel', fill = 'tozeroy') %>%
  #   add_trace(x = ~yardline_100, y = ~qb_spike, name = 'QB Spike', fill = 'tozeroy') %>%
  #   add_trace(x = ~yardline_100, y = ~run, name = 'Run', fill = 'tozeroy')
  ggplotly(
    playData() %>%
      group_by(yardline_100, play_type) %>%
      mutate(success = ifelse(epa > 0, 1, 0)) %>%
      summarize(positive = sum(success, na.rm = TRUE), plays = n()) %>%
      mutate(convert = positive/plays) %>%
      ungroup() %>%
      complete(play_type, nesting(yardline_100), fill = list(positive = 0, plays = 0, convert = 0)) %>%
      arrange(yardline_100) %>%
      ggplot(aes(x = yardline_100, y = convert, color = play_type)) + 
      geom_line()
  )
)
  

# # test dataset
# blah = reg %>%
#   filter(Season == 2019) %>%
#   filter(down == 3, game_seconds_remaining <= 900) %>%
#   select(Season, game_seconds_remaining, down, yardline_100, play_type)
# 
# # test end dataset
# test = reg %>%
#   filter(Season == 2019, down == 3, game_seconds_remaining <= 900, !is.na(play_type)) %>%
#   select(Season, game_seconds_remaining, down, yardline_100, play_type) %>%
#   group_by(yardline_100, play_type) %>%
#   summarize(plays = n()) %>%
#   ungroup() %>%
#   complete(play_type, nesting(yardline_100), fill = list(plays = 0)) %>%
#   arrange(yardline_100) %>%
#   group_by(yardline_100) %>%
#   mutate(play_pct = (plays/sum(plays))*100) %>%
#   cast(yardline_100~play_type, value = 'plays')

# main issues:
# not all play types are present in every subset, so need to adjust fill?
# likely need to use raw numbers instead of percentages
# alternatively, need to group plays by yardage, so 0-20, 20-40, 40-60, 60-80, 80-100

```

