---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(plotly)
library(reshape)
library(forcats)
library(lubridate)
library(tidytext)
library(ggjoy)
library(textdata)
```

```{r global, include=FALSE}
pre = readRDS("pre_seasons.rds")
reg = readRDS("reg_seasons.rds")
post = readRDS("post_seasons.rds")
sent = readRDS("2019_sentiments.rds")
```

Page 1
=====================================  

Column {.sidebar}
-----------------------------------------------------------------------


```{r}
selectInput("type", "Choose a game type",
            choices = c("Preseason", "Regular Season", "Postseason"))

selectInput("year", "Choose a season",
            choices = c("2009-2010" = 2009,
                        "2010-2011" = 2010,
                        "2011-2012" = 2011,
                        "2012-2013" = 2012,
                        "2013-2014" = 2013,
                        "2014-2015" = 2014,
                        "2015-2016" = 2015,
                        "2016-2017" = 2016,
                        "2017-2018" = 2017,
                        "2018-2019" = 2018,
                        "2019-2020" = 2019
                        ), 
            selected = 2019)

selectInput("dwn", "Choose a down",
            choices = c("1st Down" = 1,
                        "2nd Down" = 2,
                        "3rd Down" = 3,
                        "4th Down" = 4))

selectInput("quarter", "Choose a quarter",
            choices = c("1st Quarter" = 1,
                        "2nd Quarter" = 2,
                        "3rd Quarter" = 3,
                        "4th Quarter" = 4,
                        "Overtime" = 5))

# Add a "Show data" check box?
sliderInput("time", "Time remaining in quarter:",
                  min = 0, max = 15, value = 7)
```

Column 
-----------------------------------------------------------------------

### Chart A

```{r}
playData = reactive({
  req(input$dwn)
  req(input$year)
  req(input$time)
  switch(input$type,
         "Preseason" = pre %>%
           filter(Season == input$year, down == input$dwn, quarter_seconds_remaining <= input$time*60, !is.na(play_type), qtr == input$quarter, !(play_type %in% c("no_play", "qb_kneel", "qb_spike"))) %>%
           select(Season, down, yardline_100, play_type, epa),
         "Regular Season" = reg %>%
           filter(Season == input$year, down == input$dwn, quarter_seconds_remaining <= input$time*60, !is.na(play_type), qtr == input$quarter, !(play_type %in% c("no_play", "qb_kneel", "qb_spike"))) %>%
           select(Season, down, yardline_100, play_type, epa),
         "Postseason" = post %>%
           filter(Season == input$year, down == input$dwn, quarter_seconds_remaining <= input$time*60, !is.na(play_type), qtr == input$quarter, !(play_type %in% c("no_play", "qb_kneel", "qb_spike"))) %>%
           select(Season, down, yardline_100, play_type, epa))
})

# Need season, down, quarter_seconds_remaining, quarter, play_type, yardline_100


# For example, being on your own 20 yard line means you are 80 yards from their end zone, but being on their 20 yard line means you are 20 yards from their end zone.

renderPlotly(
    ggplotly(
      playData() %>%
      group_by(yardline_100, play_type) %>%
      mutate(success = ifelse(epa > 0, 1, 0)) %>%
      summarize(positive = sum(success, na.rm = TRUE), plays = n()) %>%
      mutate(convert = positive/plays) %>%
      ungroup() %>%
      complete(play_type, nesting(yardline_100), fill = list(positive = 0, plays = 0, convert = 0)) %>%
      arrange(yardline_100) %>%
      ggplot(aes(x = yardline_100, y = convert, color = play_type)) + 
      geom_smooth(se = FALSE, span = 0.5) + 
      geom_point()
  )
)

```

Page 2
=====================================  

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("game_type", "Choose a game type:",
            choices = c("Preseason", "Regular Season", "Postseason"))

radioButtons("quar", "Choose a quarter:",
            choices = c("1st Quarter" = 1,
                        "2nd Quarter" = 2,
                        "3rd Quarter" = 3,
                        "4th Quarter" = 4,
                        "Overtime" = 5))

radioButtons("down", "Choose a down:",
            choices = c("1st Down" = 1,
                        "2nd Down" = 2,
                        "3rd Down" = 3,
                        "4th Down" = 4))

sliderInput("yds_left", "Distance to first down:",
            min = 0, max = 10, value = 5)

sliderInput("td_left", "Distance to goal:",
            min = 0, max = 100, value = 50)

sliderInput("time_left", "Time remaining in quarter:",
                  min = 0, max = 15, value = 5)

radioButtons("play_type", "Choose a play type:",
            choices = c("Field Goal" = "field_goal",
                        "Pass" = "pass",
                        "Punt" = "punt",
                        "Run" = "run",
                        "QB Kneel" = "qb_kneel",
                        "QB Spike" = "qb_spike"
                        )
            )
selectInput("pass_len", "Choose a pass length:",
            choices = c("NA" = NA,
                        "Deep" = "deep", 
                        "Short" = "short"))

selectInput("pass_loc", "Choose a pass location:",
            choices = c("NA" = NA,
                        "Left" = "left",
                        "Middle" = "middle",
                        "Right" = "right"))

selectInput("r_gap", "Choose a run gap:",
            choices = c("NA" = NA,
                        "End" = "end", 
                        "Guard" = "guard",
                        "Tackle" = "tackle"))

selectInput("r_loc", "Choose a run location:",
            choices = c("NA" = NA,
                        "Left" = "left",
                        "Middle" = "middle",
                        "Right" = "right"))


```

```{r}
# Success = epa >= 1.0 | first_down_rush == 1 | first_down_pass == 1
# 1 point is the smallest increment of points in football, thus significant

logData = reactive({
  req(input$game_type)
  switch(input$game_type,
         "Preseason" = pre %>%
           mutate(success = ifelse((epa >= 1 | first_down_rush == 1 | first_down_pass == 1), 1, 0)),
         "Regular Season" = reg %>%
           mutate(success = ifelse((epa >= 1 | first_down_rush == 1 | first_down_pass == 1), 1, 0)),
         "Postseason" = post %>%
           mutate(success = ifelse((epa >= 1 | first_down_rush == 1 | first_down_pass == 1), 1, 0))
  )
})


renderPrint({
  df = data.frame("qtr" = as.numeric(input$quar),
                "down" = as.numeric(input$down),
                "ydstogo" = input$yds_left,
                "yardline_100" = input$td_left,
                "quarter_seconds_remaining" = input$time_left*60,
                "play_type" = input$play_type,
                "pass_length" = input$pass_len,
                "pass_location" = input$pass_loc,
                "run_gap" = input$r_gap,
                "run_location" = input$r_loc,
                stringsAsFactors = FALSE)

  if(input$play_type == "pass") {
    logreg = 
      glm(success ~ qtr + down + ydstogo + yardline_100 + quarter_seconds_remaining + pass_length + pass_location,
          data = logData() %>%
      select(qtr, down , ydstogo , yardline_100, quarter_seconds_remaining , pass_length , pass_location, success) %>%
      na.omit,
      family=binomial(link="logit"))
  }
  else if (input$play_type == "run") {
    logreg = 
      glm(success ~ qtr + down + ydstogo + yardline_100 + quarter_seconds_remaining + run_gap + run_location,
          data = logData() %>%
      select(qtr, down , ydstogo , yardline_100, quarter_seconds_remaining , run_gap , run_location, success) %>%
      na.omit,
      family=binomial(link="logit"))
  }
  else {
    logreg = 
      glm(success ~ qtr + down + ydstogo + yardline_100 + quarter_seconds_remaining + play_type,
          data = logData() %>%
      select(qtr, down , ydstogo , yardline_100, quarter_seconds_remaining , play_type, success) %>%
      na.omit,
      family=binomial(link="logit"))
  }
  
  predicted = plogis(predict(logreg, df))
  print(predicted)
})


```



Page 3
=====================================  

Column {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput("game", "Choose a playoff game",
            choices = c("AFC First Round: Tennessee Titans at New England Patriots" = 2020010401,
                        "AFC First Round: Buffalo Bills at Houston Texans" = 2020010400,
                        "NFC First Round: Seattle Seahawks at Philadelphia Eagles" = 2020010501,
                        "NFC First Round: Minnesota Vikings at New Orleans Saints" = 2010012401,
                        "AFC Second Round: Tennessee Titans at Baltimore Ravens" = 2020011101,
                        "AFC Second Round: Houston Texans at Kansas City Chiefs" = 2020011200,
                        "NFC Second Round: Seattle Seahawks at Green Bay Packers" = 2020011201,
                        "NFC Second Round: Minnesota Vikings at San Francisco 49ers" = 2020011100,
                        "AFC Championship: Tennesee Titans at Kansas City Chiefs" = 2020011900,
                        "NFC Championship: Green Bay Packers at San Francisco 49ers" = 2020011901,
                        "Super Bowl LIV: San Francisco 49ers at Kansas City Chiefs" = 2020020200
                        )
            )
```

Column 
-----------------------------------------------------------------------

### Chart A
```{r}
sentData = reactive({
  req(input$game)
  return(sent %>% filter(game_id == input$game))
})

renderPlot(
    sentData() %>%
      ggplot() +
      geom_joy(aes(
        x = Created,
        y = sentiment, 
        fill = sentiment),
        rel_min_height = 0.01,
        alpha = 0.7,
        scale = 3) +
      theme_joy() +
      labs(title = paste("/r/nfl", post$away_team[post$game_id == 2020010401][1], "at", post$home_team[post$game_id == input$game][1], "Postgame Sentiment Analysis"),
           x = "Comment Posted Time",
           y = "Sentiment") + 
      scale_fill_discrete(guide=FALSE)
)
```

